//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamlineData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpCategory()
        {
            this.ExpSubCategories = new HashSet<ExpSubCategory>();
            this.ExpSubCategories1 = new HashSet<ExpSubCategory>();
        }
    
        public int ExpenseCategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> Archive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpSubCategory> ExpSubCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpSubCategory> ExpSubCategories1 { get; set; }
    }
}
