//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamlineData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpSubCategory
    {
        public int ExpenseSubCategoryId { get; set; }
        public int ExpenseCategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public Nullable<bool> Archive { get; set; }
    
        public virtual ExpCategory ExpCategory { get; set; }
        public virtual ExpCategory ExpCategory1 { get; set; }
    }
}
