//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpCategory1
    {
        public int ExpenseCategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> Archive { get; set; }
    }
}
